__author__ = 'agopalak'

teamLocation = {
    'BUF': 'Orchard Park, NY',
    'MIA': 'Miami Gardens, FL',
    'NE': 'Foxborough, MA',
    'NYJ': 'East Rutherford, NJ',
    'BAL': 'Cleveland, OH',
    'CIN': 'Cincinnati, OH',
    'CLE': 'Cleveland, OH',
    'PIT': 'Pittsburgh, PA',
    'HOU': 'Houston, TX',
    'IND': 'Indianapolis, IN',
    'JAC': 'Jacksonville, FL',
    'TEN': 'Nashville, TN',
    'DEN': 'Denver, CO',
    'KC': 'Kansas City, MO',
    'OAK': 'Oakland, CA',
    'SD': 'San Diego, CA',
    'DAL': 'Arlington, TX',
    'NYG': 'East Rutherford, NJ',
    'PHI': 'Philadelphia, PA',
    'WAS': 'Landover, MD',
    'CHI': 'Chicago, IL',
    'DET': 'Detroit, MI',
    'GB': 'Green Bay, WI',
    'MIN': 'Minneapolis, MN',
    'ATL': 'Atlanta, GA',
    'CAR': 'Charlotte, NC',
    'NO': 'New Orleans, LA',
    'TB': 'Tampa, FL',
    'ARI': 'Glendale, AZ',
    'STL': 'St. Louis, MO',
    'SF': 'San Francisco, CA',
    'SEA': 'Seattle, WA'
}

teamStadium = {
    'BUF': 'Outdoor',
    'MIA': 'Outdoor',
    'NE': 'Outdoor',
    'NYJ': 'Outdoor',
    'BAL': 'Outdoor',
    'CIN': 'Outdoor',
    'CLE': 'Outdoor',
    'PIT': 'Outdoor',
    'HOU': 'Retractable',
    'IND': 'Retractable',
    'JAC': 'Outdoor',
    'TEN': 'Outdoor',
    'DEN': 'Outdoor',
    'KC': 'Outdoor',
    'OAK': 'Outdoor',
    'SD': 'Outdoor',
    'DAL': 'Retractable',
    'NYG': 'Outdoor',
    'PHI': 'Outdoor',
    'WAS': 'Outdoor',
    'CHI': 'Outdoor',
    'DET': 'Domed',
    'GB': 'Outdoor',
    'MIN': 'Outdoor',
    'ATL': 'Domed',
    'CAR': 'Outdoor',
    'NO': 'Domed',
    'TB': 'Outdoor',
    'ARI': 'Retractable',
    'STL': 'Domed',
    'SF': 'Outdoor',
    'SEA': 'Outdoor'
}

fieldType = {
    'BUF': 'Artificial Turf',
    'MIA': 'Grass',
    'NE': 'Field Turf',
    'NYJ': 'Field Turf',
    'BAL': 'Artificical Turf',
    'CIN': 'Field Turf',
    'CLE': 'Grass',
    'PIT': 'Grass',
    'HOU': 'Grass',
    'IND': 'Field Turf',
    'JAC': 'Grass',
    'TEN': 'Grass',
    'DEN': 'Grass',
    'KC': 'Grass',
    'OAK': 'Grass',
    'SD': 'Grass',
    'DAL': 'Artificial Turf',
    'NYG': 'Field Turf',
    'PHI': 'Grass',
    'WAS': 'Grass',
    'CHI': 'Grass',
    'DET': 'Field Turf',
    'GB': 'Grass',
    'MIN': 'Field Turf',
    'ATL': 'Field Turf',
    'CAR': 'Grass',
    'NO': 'Artificial Turf',
    'TB': 'Grass',
    'ARI': 'Grass',
    'STL': 'Field Turf',
    'SF': 'Grass',
    'SEA': 'Field Turf'
}
